export enum Colors {
    Red = "§c",
    Gold = "§6",
    Yellow = "§e",
    Green = "§a",
    Aqua = "§b",
    Blue = "§9",
    LightPurple = "§d",
    White = "§f",
    Gray = "§7",
    Black = "§0",
    DarkRed = "§4",
    DarkGreen = "§2",
    DarkAqua = "§3",
    DarkBlue = "§1",
    DarkPurple = "§5",
    DarkGray = "§8",
}